name: CI

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Run awesome-lint
        run: npx awesome-lint

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 429 --exclude localhost README.md
          fail: true
