name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Run awesome-lint
        run: npx awesome-lint

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --no-progress --accept 200,206,403,429 --exclude localhost --exclude 'npmjs\.com' README.md
          fail: true
